services:
  # bitcoind:
  #   build: ./bitcoind
  #   container_name: bitcoind
  #   restart: unless-stopped
  #   ports:
  #     - "8332:8332"   # RPC
  #     - "8333:8333"   # P2P
  #     - "28332:28332" # ZMQ raw block
  #     - "28333:28333" # ZMQ raw tx
  #   environment:
  #     - RPC_USER=${RPC_USER}
  #     - RPC_PASSWORD=${RPC_PASSWORD}
  #   volumes:
  #     - bitcoind:/home/bitcoin/.bitcoin
  #   networks:
  #     - lane-network
  #   healthcheck:
  #     test: ["CMD", "bitcoin-cli", "-rpcuser=${RPC_USER}", "-rpcpassword=${RPC_PASSWORD}", "getblockchaininfo"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #     start_period: 600s

  bitcoin-cache:
    image: ghcr.io/lanelayer/core-lane/core-lane:latest
    container_name: bitcoin-cache
    restart: unless-stopped
    ports:
      - "8332:8332"   # Bitcoin Cache RPC
    command: >
      /app/core-lane-node bitcoin-cache
      --host 0.0.0.0
      --port 8332
      --cache-dir /cache
      --bitcoin-rpc-url https://bitcoin-rpc.publicnode.com
      --block-archive http://144.76.56.210/blocks
      --starting-block-count 916201
      --no-rpc-auth
    volumes:
      - bitcoin-cache:/cache
    networks:
      - lane-network

  core-lane:
    image: ghcr.io/lanelayer/core-lane/core-lane:latest
    container_name: core-lane
    depends_on:
      - bitcoin-cache
    ports:
      - "8545:8545"   # Core Lane RPC
    environment:
      - CORE_LANE_MNEMONIC=${CORE_LANE_MNEMONIC}
      - NETWORK=${NETWORK:-mainnet}
      - ELECTRUM_URL=${ELECTRUM_URL:-ssl://electrum.blockstream.info:50002}
    command: >
      sh -c "
      /app/core-lane-node start
      --data-dir /data
      --bitcoin-rpc-read-url http://bitcoin-cache:8332
      --bitcoin-rpc-read-user ${RPC_USER}
      --bitcoin-rpc-read-password ${RPC_PASSWORD}
      --bitcoin-rpc-write-url http://bitcoin-cache:8332
      --bitcoin-rpc-write-user ${RPC_USER}
      --bitcoin-rpc-write-password ${RPC_PASSWORD}
      --start-block 916201
      --rpc-wallet hot
      --mnemonic \"$$CORE_LANE_MNEMONIC\"
      --electrum-url \"$$ELECTRUM_URL\"
      --http-host 0.0.0.0
      --http-port 8545
      "
    volumes:
      - core-lane:/data  # Persist wallet database and state
    restart: unless-stopped
    networks:
      - lane-network

networks:
  lane-network:
    driver: bridge

volumes:
  # bitcoind:
  bitcoin-cache:
  core-lane:  # Stores wallet databases (wallet_<network>.sqlite3) and state