name: Build and Push Docker Image

on:
  push:
    branches: 
    -main
  pull_request:
    branches:
    -main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Test Docker build
      run: |
        echo "✅ Build successful"